# Generated by Django 3.2.1 on 2021-05-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_author_follow_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
    ]
